### ISSUE TITLE
Support for 4 coming soon?

### ISSUE THREAD

**Issue by drkpxl** [fredjean/middleman-s3_redirect#14]
`Please report a bug if this causes problems.
/Users/stevenwork/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:96:in `load': Tried to activate old-style extension: s3_redirect. They are no longer supported. (RuntimeError)
    from /Users/stevenwork/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:127:in `block in load_settings'
    from /Users/stevenwork/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:125:in `each'
    from /Users/stevenwork/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:125:in `load_settings'
    from /Users/stevenwork/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.9/lib/middleman-core/extension_manager.rb:12:in `initialize'
    from /Users/stevenwork/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.9/lib/middleman-core/application.rb:262:in `new'
    from /Users/stevenwork/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.9/lib/middleman-core/application.rb:262:in `initialize'
    from /Users/stevenwork/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.9/bin/middleman:51:in `new'
    from /Users/stevenwork/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.9/bin/middleman:51:in `<top (required)>'
    from /Users/stevenwork/.rbenv/versions/2.2.5/bin/middleman:23:in `load'
    from /Users/stevenwork/.rbenv/versions/2.2.5/bin/middleman:23:in `<main>`

Currently using:
`Middleman 4.1.9`

Or should I look elsewhere? I love your S3_Sync gem and use it in production on a few sites!

**Comment by umerebryx** [comment]
Any update on this? I getting same error with:
> Traceback (most recent call last):
	10: from /Users/umerkhan/.rbenv/versions/2.5.3/bin/middleman:23:in `<main>'
	 9: from /Users/umerkhan/.rbenv/versions/2.5.3/bin/middleman:23:in `load'
	 8: from /Users/umerkhan/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/middleman-cli-4.3.4/bin/middleman:49:in `<top (required)>'
	 7: from /Users/umerkhan/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/middleman-cli-4.3.4/bin/middleman:49:in `new'
	 6: from /Users/umerkhan/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/application.rb:263:in `initialize'
	 5: from /Users/umerkhan/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/application.rb:263:in `new'
	 4: from /Users/umerkhan/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/extension_manager.rb:12:in `initialize'
	 3: from /Users/umerkhan/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/extensions.rb:125:in `load_settings'
	 2: from /Users/umerkhan/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/extensions.rb:125:in `each'
	 1: from /Users/umerkhan/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/extensions.rb:127:in `block in load_settings'
/Users/umerkhan/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/extensions.rb:96:in `load': Tried to activate old-style extension: s3_redirect. They are no longer supported. (RuntimeError)
